language: python
python:
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements.txt
script:
  - make web
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _build
  target-branch: master
  fqdn: eissenhauer.com
  on:
    branch: deploy
